export const frameworks=['DORA','FCA-OR','ISO-27001','PCI-DSS'];
export const risks=Array.from({length:10},(_,i)=>({ref:`R-${String(i+1).padStart(3,'0')}`,title:['Payment outage','Cloud concentration','AML screening failure','PCI data exposure','Third-party insolvency','Privileged access','Regulatory reporting','Fraud spike','Change failure','BCP shortfall'][i],category:['Operational','Technology','Compliance','Cyber','Third Party'][i%5],status:i%3?'Open':'Mitigating',score:25-i*2,links:{controls:2+i%3,incidents:i%2,issues:1,requirements:3,vendors:i%4}}));
export const controls=Array.from({length:15},(_,i)=>({ref:`C-${String(i+1).padStart(3,'0')}`,name:['Access recertification','PCI key rotation','DORA incident playbook','Vendor exit plan','KRI breach review'][i%5]+' '+(i+1),type:['Preventive','Detective','Corrective'][i%3],frequency:['Monthly','Quarterly','Annual'][i%3],effectiveness:['Effective','Partially effective','Ineffective'][i%3]}));
export const incidents=Array.from({length:5},(_,i)=>({ref:`INC-${String(i+1).padStart(3,'0')}`,title:['Card processor latency','PII mailbox misroute','Core ledger degradation','Screening queue backlog','Cloud region failover'][i],severity:['P1','P2','P3','P2','P4'][i],dora:i<3,status:i%2?'Closed':'Open'}));
export const issues=Array.from({length:10},(_,i)=>({ref:`ISS-${String(i+1).padStart(3,'0')}`,title:['Evidence gap','Policy overdue','Control failure','Vendor SLA exception','Audit observation'][i%5]+' '+(i+1),severity:['High','Medium','Low'][i%3],overdue:i%4===0,source:['Audit','KRI','Incident','Compliance'][i%4]}));
export const vendors=Array.from({length:37},(_,i)=>({name:['AWS','Visa','Mastercard','Onfido','Snowflake','Twilio'][i%6]+' '+(i+1),tier:['Critical','High','Medium','Low'][i%4],ict:i%2===0,concentration:i%7===0}));
export const kris=Array.from({length:12},(_,i)=>({name:['P1 incidents','Failed controls','Overdue issues','Vendor SLA misses'][i%4]+' '+(i+1),rag:['Green','Amber','Red'][i%3],value:Math.round(20+i*6)}));
export const modules={Risk:['Risks','Risk Appetite','Heat Map','KRIs'],Compliance:['Frameworks','Policies'],Operations:['Incidents','Vendors','Operational Resilience'],Governance:['Governance','Audit','Templates'],Admin:['Integrations','Settings']};
export function stats(){return {risks:risks.length,controls:controls.length,incidents:incidents.length,issues:issues.length,vendors:vendors.length,frameworks:frameworks.length}}
